version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [type:chore]
    groups:
      npm:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels: [type:chore]
    groups:
      cargo:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [type:ci]
